/**
 * Convergence between measured movement screens and the measured delivery.
 *
 * Two independent measurements of the same athlete: what their body can do
 * (screens) and what their body actually did (the pitch). Running the
 * comparison in both directions is far stronger than either source alone --
 * but only if the check is allowed to come back negative.
 *
 * THE DESIGN CONSTRAINT THAT MAKES THIS HONEST:
 * Every prediction below is written as static code with its confirming AND
 * refuting condition fixed in advance. It is not generated by a model that has
 * already seen the delivery. Told "this athlete has a tight upper back, go
 * look for early rotation," a model finds early rotation essentially every
 * time -- producing a system that manufactures agreement, looks extremely
 * convincing, and proves nothing. Committing the prediction in code first is
 * what makes a disagreement possible, and disagreements are where the value is.
 *
 * The three outcomes are all useful:
 *  - CONFIRMED: screen limitation and delivery signature agree. Strongest
 *    finding available, and what training should attack first.
 *  - NOT_SHOWING: real screen limitation the delivery is not currently paying
 *    for. Lower training priority than something actively affecting the throw.
 *  - UNEXPLAINED: delivery fault with no measured physical limitation behind
 *    it. Points to skill and timing work rather than mobility or strength.
 *
 * Nothing here diagnoses. A limitation absent from one clip is never "ruled
 * out" -- compensations vary pitch to pitch -- only lower priority right now.
 */

import {
  MOVEMENT_SCREENS,
  classifyScreenValue,
  getMovementScreen,
  type ScreenResult,
} from './movement-screens'

/** The delivery-side measurements a prediction can be tested against. */
export type DeliveryMetrics = {
  /** Lead-knee angle change after foot strike, degrees. */
  kneeChangeAfterStride: number | null
  /** Trunk-angle change across the delivery, degrees. */
  trunkTiltChange: number | null
  /** Throwing-elbow angle range across the delivery, degrees. */
  elbowChange: number | null
  /** Peak hip-shoulder separation, degrees. */
  peakSeparation: number | null
  /** When peak separation happened, seconds. */
  peakSeparationTime: number | null
  /** Front-foot contact time, seconds. */
  strideTime: number | null
}

export type ConvergenceOutcome = 'confirmed' | 'not_showing' | 'inconclusive'

export type ConvergenceCheck = {
  screen_id: string
  screen_name: string
  /** What this limitation was predicted to do to the delivery. */
  prediction: string
  outcome: ConvergenceOutcome
  /** Plain-language statement of what the delivery actually showed. */
  observed: string
  /** What this means for training priority. */
  implication: string
  /** Training priority weight; higher is more urgent. */
  priority: number
}

export type UnexplainedFault = {
  category: string
  score: number
  observed: string
  implication: string
}

export type ConvergenceReport = {
  checks: ConvergenceCheck[]
  unexplained: UnexplainedFault[]
  /** True when screens or delivery data were too thin to compare at all. */
  insufficient: boolean
}

type Prediction = {
  screenId: string
  /** Plain-language mechanical signature this limitation should produce. */
  predicts: string
  /**
   * Evaluated ONLY after the prediction above is fixed. Returns 'confirmed'
   * when the delivery shows the predicted signature, 'not_showing' when the
   * delivery clearly does not, and 'inconclusive' when the measurement needed
   * is missing or sits between the two thresholds.
   */
  evaluate: (metrics: DeliveryMetrics) => { outcome: ConvergenceOutcome; observed: string }
  /** Mechanics categories this limitation could plausibly explain. */
  explains: string[]
}

function describeDegrees(value: number | null): string {
  return value === null ? 'not measured' : `${Math.round(value)}°`
}

/**
 * Static prediction table. Thresholds are deliberately coarse and leave a
 * middle band that returns 'inconclusive' rather than forcing every clip into
 * agreement or disagreement.
 */
const PREDICTIONS: Prediction[] = [
  {
    screenId: 'seated_trunk_rotation',
    predicts:
      'If the upper back cannot rotate far on its own, the shoulders tend to turn with the hips instead of staying closed, so the trunk opens early and total separation stays small.',
    explains: ['Upper-Half Timing', 'Posture'],
    evaluate(metrics) {
      const { peakSeparation, peakSeparationTime, strideTime } = metrics
      if (peakSeparation === null) {
        return { outcome: 'inconclusive', observed: 'Trunk separation could not be measured in this delivery.' }
      }
      const openedEarly =
        peakSeparationTime !== null && strideTime !== null && peakSeparationTime < strideTime - 0.08
      if (peakSeparation < 25 || openedEarly) {
        return {
          outcome: 'confirmed',
          observed: openedEarly
            ? `Peak separation was ${describeDegrees(peakSeparation)} and it happened before the front foot landed, which is the early-opening pattern this limitation predicts.`
            : `Peak separation reached only ${describeDegrees(peakSeparation)}, which is the small-separation pattern this limitation predicts.`,
        }
      }
      if (peakSeparation >= 30) {
        return {
          outcome: 'not_showing',
          observed: `Separation reached ${describeDegrees(peakSeparation)} and did not peak early, so the delivery is not currently paying for this limitation.`,
        }
      }
      return {
        outcome: 'inconclusive',
        observed: `Separation reached ${describeDegrees(peakSeparation)}, which sits between the two patterns and does not settle the question.`,
      }
    },
  },
  {
    screenId: 'seated_hip_rotation',
    predicts:
      'If a hip is short on rotation, the pelvis struggles to clear the front leg, which usually shows up as reduced separation between the hips and shoulders.',
    explains: ['Lower-Half Sequencing', 'Direction'],
    evaluate(metrics) {
      const { peakSeparation } = metrics
      if (peakSeparation === null) {
        return { outcome: 'inconclusive', observed: 'Trunk separation could not be measured in this delivery.' }
      }
      if (peakSeparation < 25) {
        return { outcome: 'confirmed', observed: `Separation peaked at ${describeDegrees(peakSeparation)}, consistent with a pelvis that is not clearing the front leg.` }
      }
      if (peakSeparation >= 32) {
        return { outcome: 'not_showing', observed: `Separation reached ${describeDegrees(peakSeparation)}, so the hips are clearing well enough in this delivery.` }
      }
      return { outcome: 'inconclusive', observed: `Separation reached ${describeDegrees(peakSeparation)}, which is not decisive either way.` }
    },
  },
  {
    screenId: 'ankle_dorsiflexion',
    predicts:
      'If the lead ankle cannot let the shin travel forward, the landing leg tends to straighten out instead of absorbing, so the lead knee keeps changing angle after foot strike.',
    explains: ['Front-Side Stability', 'Lower-Half Sequencing'],
    evaluate(metrics) {
      const { kneeChangeAfterStride } = metrics
      if (kneeChangeAfterStride === null) {
        return { outcome: 'inconclusive', observed: 'Lead-knee movement after landing could not be measured.' }
      }
      if (kneeChangeAfterStride > 35) {
        return { outcome: 'confirmed', observed: `The lead knee changed ${describeDegrees(kneeChangeAfterStride)} after landing, the unstable-landing pattern this limitation predicts.` }
      }
      if (kneeChangeAfterStride <= 22) {
        return { outcome: 'not_showing', observed: `The lead knee only changed ${describeDegrees(kneeChangeAfterStride)} after landing, so the landing is holding up despite the limitation.` }
      }
      return { outcome: 'inconclusive', observed: `The lead knee changed ${describeDegrees(kneeChangeAfterStride)} after landing, which is borderline.` }
    },
  },
  {
    screenId: 'active_straight_leg_raise',
    predicts:
      'If the hamstring restricts how far the leg travels, the lead leg tends not to block cleanly at foot strike, so the front knee keeps moving instead of giving a steady base.',
    explains: ['Front-Side Stability', 'Lower-Half Sequencing'],
    evaluate(metrics) {
      const { kneeChangeAfterStride } = metrics
      if (kneeChangeAfterStride === null) {
        return { outcome: 'inconclusive', observed: 'Lead-knee movement after landing could not be measured.' }
      }
      if (kneeChangeAfterStride > 35) {
        return { outcome: 'confirmed', observed: `The lead knee changed ${describeDegrees(kneeChangeAfterStride)} after landing, the soft-block pattern this limitation predicts.` }
      }
      if (kneeChangeAfterStride <= 22) {
        return { outcome: 'not_showing', observed: `The lead knee held to ${describeDegrees(kneeChangeAfterStride)} of change after landing, so the block is working despite the limitation.` }
      }
      return { outcome: 'inconclusive', observed: `The lead knee changed ${describeDegrees(kneeChangeAfterStride)} after landing, which is borderline.` }
    },
  },
  {
    screenId: 'single_leg_stance',
    predicts:
      'If the pelvis drops when standing on one leg, the front side tends to give way after landing, which shows up as the trunk tipping through the finish.',
    explains: ['Front-Side Stability', 'Posture'],
    evaluate(metrics) {
      const { trunkTiltChange } = metrics
      if (trunkTiltChange === null) {
        return { outcome: 'inconclusive', observed: 'Trunk-angle change could not be measured in this delivery.' }
      }
      if (trunkTiltChange > 25) {
        return { outcome: 'confirmed', observed: `Trunk angle changed ${describeDegrees(trunkTiltChange)} through the delivery, consistent with a front side that is not holding.` }
      }
      if (trunkTiltChange <= 14) {
        return { outcome: 'not_showing', observed: `Trunk angle only changed ${describeDegrees(trunkTiltChange)}, so posture is holding up despite the drop measured standing still.` }
      }
      return { outcome: 'inconclusive', observed: `Trunk angle changed ${describeDegrees(trunkTiltChange)}, which is borderline.` }
    },
  },
  {
    screenId: 'overhead_reach',
    predicts:
      'If the arm cannot travel fully overhead, the trunk usually leans to make room for the arm, which shows up as a larger trunk-angle change during the throw.',
    explains: ['Posture', 'Upper-Half Timing'],
    evaluate(metrics) {
      const { trunkTiltChange } = metrics
      if (trunkTiltChange === null) {
        return { outcome: 'inconclusive', observed: 'Trunk-angle change could not be measured in this delivery.' }
      }
      if (trunkTiltChange > 25) {
        return { outcome: 'confirmed', observed: `Trunk angle changed ${describeDegrees(trunkTiltChange)}, consistent with the trunk making room for a restricted arm path.` }
      }
      if (trunkTiltChange <= 14) {
        return { outcome: 'not_showing', observed: `Trunk angle only changed ${describeDegrees(trunkTiltChange)}, so the trunk is not visibly compensating for it here.` }
      }
      return { outcome: 'inconclusive', observed: `Trunk angle changed ${describeDegrees(trunkTiltChange)}, which is borderline.` }
    },
  },
]

/** Screens measuring 'limited' or 'watch' on either side. */
function limitedScreenIds(results: ScreenResult[]): Set<string> {
  const limited = new Set<string>()
  for (const result of results) {
    const screen = getMovementScreen(result.screen_id)
    if (!screen || result.value === null) continue
    const classification = classifyScreenValue(screen, result.value)
    if (classification === 'limited' || classification === 'watch') limited.add(screen.id)
  }
  return limited
}

export type WeakCategory = { category: string; score: number }

/**
 * Runs both directions of the comparison.
 *
 * Forward: each measured limitation predicts a delivery signature, which is
 * then checked. Reverse: each weak mechanics category is checked for whether
 * any measured limitation could explain it at all.
 */
export function buildConvergenceReport(
  screenResults: ScreenResult[],
  metrics: DeliveryMetrics,
  weakCategories: WeakCategory[] = [],
): ConvergenceReport {
  const measured = screenResults.filter((item) => item.value !== null).length
  const hasDeliveryData =
    metrics.kneeChangeAfterStride !== null ||
    metrics.trunkTiltChange !== null ||
    metrics.peakSeparation !== null

  if (measured < 4 || !hasDeliveryData) {
    return { checks: [], unexplained: [], insufficient: true }
  }

  const limited = limitedScreenIds(screenResults)

  const checks: ConvergenceCheck[] = []
  for (const prediction of PREDICTIONS) {
    if (!limited.has(prediction.screenId)) continue
    const screen = getMovementScreen(prediction.screenId)
    if (!screen) continue
    const { outcome, observed } = prediction.evaluate(metrics)
    checks.push({
      screen_id: prediction.screenId,
      screen_name: screen.name,
      prediction: prediction.predicts,
      outcome,
      observed,
      implication:
        outcome === 'confirmed'
          ? 'Two independent measurements agree, so this is the strongest finding available and should be trained first.'
          : outcome === 'not_showing'
            ? 'The limitation is real but this delivery is not currently paying for it. Keep it in the plan at lower priority and re-check it at the next video, since compensations vary from pitch to pitch. It should not be treated as the main problem right now.'
            : 'The delivery measurement was missing or sat between the two patterns, so this stays an open question for the next check.',
      priority: outcome === 'confirmed' ? 3 : outcome === 'inconclusive' ? 1.5 : 1,
    })
  }

  // Reverse direction: a weak category with no measured limitation behind it.
  const explainedCategories = new Set(
    PREDICTIONS.filter((prediction) => limited.has(prediction.screenId)).flatMap((prediction) => prediction.explains),
  )
  const unexplained: UnexplainedFault[] = weakCategories
    .filter((item) => item.score <= 2 && !explainedCategories.has(item.category))
    .map((item) => ({
      category: item.category,
      score: item.score,
      observed: `${item.category} scored ${item.score}/5, but none of the movement screens found a physical limitation that would explain it.`,
      implication:
        'With no measured physical restriction behind it, this is more likely a timing or skill pattern than a mobility or strength problem. Drill and cue work should come before adding more lifting or stretching for it.',
    }))

  checks.sort((a, b) => b.priority - a.priority)

  return { checks, unexplained, insufficient: false }
}

/** Screens that have a prediction defined. Used by tests and tooling. */
export const PREDICTED_SCREEN_IDS = PREDICTIONS.map((prediction) => prediction.screenId)

/** Guards against a screen being added without anyone deciding what it predicts. */
export function screensWithoutPredictions(): string[] {
  return MOVEMENT_SCREENS.filter((screen) => !PREDICTED_SCREEN_IDS.includes(screen.id)).map((screen) => screen.id)
}
