-- Pitch Nav drill library.
--
-- Built to match the system rather than sit beside it:
--   - Every throwing category the scorecard can flag has at least three
--     drills, because the plan picks a primary drill and a separate
--     repeatability drill and they must not collide.
--   - Every movement screen has a mobility drill that addresses what it
--     measures, so a measured limitation always has something to prescribe.
--   - Strength entries line up with the physical causes the assessment can
--     name, so a hamstring finding and a thoracic finding lead somewhere
--     different.
--
-- These are established, widely used drills described plainly. Nothing here
-- is exotic and nothing is invented. Every entry carries an honest safety
-- note. They should still be reviewed by a coach before release -- the point
-- of the library is that the app selects from movements a human approved.
--
-- Safe to run more than once: existing drills are skipped by name.

with seed(name, category, description, trains, athlete_type, sets, reps, cues, mistakes, safety) as (
  values
  -- ── Direction: where the stride goes and whether it repeats ──────────
  ('Tape-Line Stride','direction','Lay a straight line from the rubber toward the target. Complete your normal delivery and check where the front foot lands relative to the line each rep.','Repeatable stride direction','Youth through adult',3,'6 dry reps',array['Look at the line only after you finish','Let the stride happen naturally'],array['Aiming the foot instead of moving naturally','Changing the whole delivery to chase the line'],'Dry reps or light throws only. Use a flat, non-slip surface.'),
  ('Two-Cone Stride Corridor','direction','Place a cone just inside and just outside your normal landing spot. Stride between them without touching either.','Landing consistency','High school through adult',3,'5 reps',array['Keep effort moderate','Reset fully between reps'],array['Shortening the stride to stay safe','Staring at the cones during the move'],'Use soft cones. Stop if the stride feels forced.'),
  ('Walk-In Delivery','direction','Take two slow walking steps into your normal delivery so momentum carries you toward the target.','Momentum toward the target','High school through adult',3,'5 throws',array['Let the walk set the direction','Stay under control'],array['Rushing the walk-in','Landing across the body'],'Use a clear throwing lane at low to moderate intensity.'),
  ('Closed-Eyes Stride Check','direction','Set up normally, close your eyes, and complete a dry stride. Open them at landing to see where you finished.','Internal awareness of direction','High school through adult',2,'5 dry reps',array['Trust the move','Notice where you actually landed'],array['Peeking early','Doing this near obstacles'],'Dry reps only, in a clear open space. Never with a ball.'),

  -- ── Rhythm: the tempo of the whole move ─────────────────────────────
  ('Rocker Step Repeats','rhythm','Use a small rocker step into your delivery and repeat it continuously, keeping the same tempo each time.','Consistent delivery tempo','Youth through adult',3,'5 throws',array['Keep the same count every rep','Stay smooth rather than fast'],array['Speeding up as the set goes on','Pausing at the top'],'Low to moderate intensity. Stop if timing degrades.'),
  ('Count-Tempo Throws','rhythm','Give your delivery a simple count and hold that count across every rep in the set.','Repeatable timing','Youth through adult',3,'6 throws',array['Say the count out loud at first','Keep the count identical every rep'],array['Letting the count drift with effort','Counting faster when tired'],'Keep intensity moderate so the count stays honest.'),
  ('Continuous Windup','rhythm','Complete your windup and go straight into the next one without a full reset, keeping the motion smooth.','Rhythm under mild fatigue','High school through adult',2,'4 reps',array['Stay smooth as reps add up','Stop the set when tempo changes'],array['Continuing after the move falls apart','Adding intent to fight fatigue'],'Keep volume low. This is a rhythm drill, not conditioning.'),

  -- ── Lower-half sequencing: the order the move happens in ────────────
  ('Knee-Up Hold to Stride','lower_half_sequencing','Reach your normal leg lift, hold it under control for two counts, then complete the stride.','Controlled start to the delivery','Youth through adult',3,'5 reps',array['Balance over the back leg','Start the stride from the hips'],array['Rushing out of the hold','Leaning back to balance'],'Use a stable surface. Reduce hold time if balance is poor.'),
  ('Hip-Hinge Load and Go','lower_half_sequencing','From the top of the leg lift, hinge slightly at the hips into the stride so the lower half leads.','Hips leading the delivery','High school through adult',3,'5 reps',array['Feel the back hip load','Let the hips move before the shoulders'],array['Bending at the waist instead of the hips','Sitting straight down'],'Keep range comfortable and pain-free.'),
  ('Walking Windup','lower_half_sequencing','Take slow, deliberate walking steps into your delivery so the lower half is already moving before the arm.','Ground-up sequencing','High school through adult',3,'5 throws',array['Let the legs start the motion','Keep the arm relaxed until the legs finish'],array['Overstriding','Throwing before the feet organize'],'Start at low intensity in a safe throwing lane.'),
  ('Step-Back Load','lower_half_sequencing','Take a controlled step back with the stride leg, then load into your normal delivery from there.','Loading the back hip','High school through adult',3,'5 reps',array['Stay balanced through the step back','Load into the back hip, not the back knee'],array['Stepping back too far','Losing posture on the load'],'Keep the step modest and controlled.'),

  -- ── Lead-leg stability: what the front side does after landing ──────
  ('Lead-Leg Landing Hold','lead_leg_stability','Complete your stride and hold the landing position for three counts without letting the front knee drift.','A firmer front side','High school through adult',3,'5 reps each side',array['Freeze at landing','Keep the knee over the foot'],array['Locking the knee hard','Collapsing into the hold'],'Aim for a firm base, not a rigid locked knee. Stop on pain.'),
  ('Single-Leg Landing Stick','lead_leg_stability','From a small hop, land on the lead leg and stick the landing for two counts.','Absorbing landing force','High school through adult',3,'5 each side',array['Land softly through the whole foot','Stop the movement completely'],array['Landing stiff-legged','Hopping too far'],'Keep the hop small. Use a flat, non-slip surface.'),
  ('Front-Leg Block Dry Reps','lead_leg_stability','Complete a dry delivery focused only on the front leg bracing at landing so the hips can rotate around it.','Lead-leg blocking','High school through adult',3,'6 dry reps',array['Let the leg accept the weight, then hold','Rotate around the front leg'],array['Straightening the leg violently','Letting the knee keep travelling forward'],'Dry reps only. Build gradually and stop on any knee pain.'),
  ('Lateral Step-Down Control','lead_leg_stability','Stand on a low step, lower the other foot slowly to the ground under control, then return.','Single-leg control','Youth through adult',3,'6 each side',array['Lower slowly','Keep the hips level'],array['Dropping quickly','Letting the standing hip collapse'],'Use a low, stable step. Hold support if needed.'),

  -- ── Trunk rotation: separation between hips and shoulders ───────────
  ('Hip-Lead Separation Dry Reps','trunk_rotation','From the top of the leg lift, start the hips toward the target while keeping the shoulders closed a moment longer.','Hip-to-shoulder separation','High school through adult',3,'6 dry reps',array['Hips first, shoulders after','Keep the glove side quiet'],array['Turning everything at once','Forcing the shoulders back'],'Dry reps first. Keep range comfortable and pain-free.'),
  ('Seated Rotational Throw','trunk_rotation','Sitting down removes the lower half, so the throw comes from trunk rotation alone. Throw at light effort into a net.','Trunk-driven rotation','High school through adult',3,'6 throws',array['Rotate the chest, do not pull with the arm','Stay tall through the trunk'],array['Using arm effort to compensate','Throwing hard'],'Light effort only, into a net. Not for anyone with back or shoulder pain.'),
  ('Medicine-Ball Shotput','trunk_rotation','From an athletic stance, drive a light medicine ball toward a wall using the legs and trunk together.','Rotational power transfer','High school through adult',3,'5 each side',array['Drive from the ground','Finish balanced'],array['Using arms only','Using a ball that is too heavy'],'Clear the area and use a wall rated for medicine-ball work.'),
  ('Glove-Side Hold','trunk_rotation','Complete your delivery while keeping the glove arm firm out front rather than letting it fly open.','Holding the front side closed','Youth through adult',3,'6 reps',array['Pull the chest to the glove','Keep the glove in front of the chest'],array['Yanking the glove to the ribs','Locking the glove arm rigid'],'Keep effort moderate while the pattern is new.'),

  -- ── Arm timing: when the arm arrives relative to the body ───────────
  ('Hand-Break Timing Dry Reps','arm_timing','Complete dry deliveries focused only on breaking the hands at the same point in the move every rep.','Repeatable hand break','Youth through adult',3,'6 dry reps',array['Break the hands at the same spot every time','Keep the break smooth'],array['Yanking the hands apart','Breaking late and rushing the arm'],'Dry reps only. Stop if the shoulder feels rushed.'),
  ('Wall Arm-Path Trace','arm_timing','Stand close to a wall and trace your arm path slowly without contacting it, checking the path is the same each rep.','Arm-path awareness','High school through adult',2,'8 slow reps',array['Move slowly','Repeat the same path'],array['Rushing the trace','Forcing an unnatural path'],'Slow, pain-free movement only. Do not contact the wall.'),
  ('Pivot Pickoff Throw','arm_timing','From a set position, pivot and make a controlled throw so the arm has to arrive on time with a shortened lower half.','Arm arriving on time','High school through adult',3,'5 throws',array['Let the feet finish before the arm','Stay compact'],array['Throwing before the feet land','Overthrowing the drill'],'Moderate intensity in a clear throwing lane.'),
  ('Two-Count Arm Sync','arm_timing','Use a two-count so the front foot lands on one and the arm reaches the throwing position on two.','Syncing arm to foot strike','High school through adult',3,'6 reps',array['Foot lands on one','Arm is up on two'],array['Letting the arm lag past the count','Speeding the count up'],'Start dry, then add light throws once the timing holds.'),

  -- ── Deceleration: what happens after release ────────────────────────
  ('Finish and Field','deceleration','Complete the throw and move straight into a balanced fielding position rather than stopping abruptly.','Controlled follow-through','Youth through adult',3,'6 throws',array['Let the arm finish across the body','End balanced and ready'],array['Cutting the finish short','Stopping the arm deliberately'],'Never brake the arm on purpose. Let it decelerate naturally.'),
  ('Band Deceleration Pull','deceleration','Using a light band anchored in front, control the band back through your finish path slowly.','Deceleration strength','High school through adult',3,'8 each side',array['Control the return, do not let it snap','Stay smooth'],array['Using a heavy band','Letting the band pull the arm back fast'],'Light band only. Stop immediately on shoulder pain.'),
  ('Reverse-Step Finish','deceleration','After release, allow a controlled step through so momentum is absorbed by the legs rather than the arm.','Absorbing finish momentum','High school through adult',3,'6 throws',array['Let the back leg come through','Absorb with the legs'],array['Fighting the momentum','Landing stiff'],'Clear space behind the landing area.'),

  -- ── Command: where the ball goes ────────────────────────────────────
  ('Target Box Focus','command','Pick a small, specific target and commit to it before every pitch. Track how often you hit it.','Target commitment','Youth through adult',3,'10 throws',array['Choose the spot before the windup starts','Commit fully'],array['Picking the target late','Changing the target mid-delivery'],'Normal throwing workload only. Respect your pitch count.'),
  ('Corner Ladder','command','Work one corner of the zone for a set of throws, then switch, keeping delivery identical.','Locating without changing mechanics','High school through adult',3,'6 each side',array['Same delivery for both corners','Aim with direction, not by steering'],array['Steering the ball with the hand','Changing arm slot per corner'],'Count these toward your weekly throwing volume.'),
  ('Two-Target Alternation','command','Alternate between two targets every throw so you never repeat the same one twice in a row.','Adjusting between pitches','High school through adult',3,'8 throws',array['Reset fully between throws','Commit to each target'],array['Rushing between throws','Losing the delivery to chase the target'],'Keep intensity moderate and respect pitch counts.'),

  -- ── Mobility: one per movement screen ───────────────────────────────
  ('Supine Leg Lower','mobility','Lying on your back, lower one straight leg slowly to the floor while keeping the other leg still. Addresses the Active Straight Leg Raise screen.','Hamstring range and control','Youth through adult',3,'6 each side',array['Lower slowly','Keep the down leg flat'],array['Rushing the lower','Letting the low back arch'],'Move within a comfortable, pain-free range.'),
  ('Wall Slide with Lift-Off','mobility','With forearms on a wall, slide them upward and briefly lift them away at the top. Addresses the Overhead Reach screen.','Overhead shoulder range','Youth through adult',3,'8 reps',array['Keep the ribs down','Move slowly'],array['Arching the low back to gain height','Shrugging at the top'],'Stay pain-free. Reduce range rather than forcing it.'),
  ('Knee-to-Wall Ankle Rocker','mobility','In a split stance facing a wall, drive the front knee toward the wall keeping the heel flat. Addresses the Ankle Bend screen.','Ankle range','Youth through adult',3,'8 each side',array['Keep the heel down','Drive the knee over the middle of the foot'],array['Letting the heel lift','Collapsing the arch'],'Comfortable range only. Stop on ankle pain.'),
  ('90/90 Hip Switches','mobility','Seated with both knees bent at right angles, rotate the hips from one side to the other under control. Addresses the Seated Hip Rotation screen.','Hip rotation range','Youth through adult',3,'6 each side',array['Stay tall through the trunk','Move slowly'],array['Using momentum','Rounding the low back'],'Move in a pain-free range. Reduce range if the hip pinches.'),
  ('Open-Book Thoracic Rotation','mobility','Lying on your side with knees bent, open the top arm across your body and follow it with your eyes. Addresses the Seated Trunk Rotation screen.','Upper-back rotation','Youth through adult',3,'6 each side',array['Keep the knees stacked and still','Let the chest lead'],array['Rotating from the low back','Forcing the shoulder to the floor'],'Gentle, pain-free range only.'),
  ('Half-Kneeling Hip-Flexor Mobilization','mobility','In a half-kneeling position, gently tuck the pelvis and shift forward slightly. Addresses the Hip Extension screen.','Front-of-hip range','Youth through adult',3,'5 each side, 20 seconds',array['Tuck the pelvis before shifting','Squeeze the back glute'],array['Arching the low back','Shifting too far forward'],'Pad the down knee. Keep it gentle and pain-free.'),
  ('Prone Shoulder Rotation at 90','mobility','Lying face down with the arm out at shoulder height and elbow bent, rotate the forearm up and down slowly. Addresses the Shoulder Lay-Back screen.','Shoulder rotation range','High school through adult',3,'8 each side',array['Move slowly','Keep the upper arm still'],array['Letting the shoulder roll forward','Forcing the end range'],'No load and no forcing. Stop immediately on shoulder pain.'),
  ('Cross-Body Reach Mobilization','mobility','Bring the arm gently across the chest and hold, keeping the shoulder blade relaxed. Addresses the Cross-Body Reach screen.','Back-of-shoulder range','High school through adult',3,'4 each side, 20 seconds',array['Keep the shoulder down','Breathe out into the hold'],array['Pulling hard on the elbow','Shrugging the shoulder up'],'Gentle hold only. Stop on any pinching in the shoulder.'),
  ('Deep Squat Hold','mobility','Lower into a comfortable deep squat with heels down and hold, gently working the range. Addresses the Squat Depth screen.','Combined lower-body range','Youth through adult',3,'3 holds of 20 seconds',array['Keep the heels down','Stay tall through the chest'],array['Letting the heels lift','Forcing depth that is not there yet'],'Hold a support if needed. Comfortable range only.'),

  -- ── Strength and power: matched to the physical causes ──────────────
  ('Single-Leg Romanian Deadlift','strength_power','Hinge at the hips on one leg with a light load, keeping a long spine, then return.','Hamstring strength and hip hinge','High school through adult',3,'6 each side',array['Hinge, do not squat','Keep the hips level'],array['Rounding the back','Using too much load'],'Start with bodyweight. Use appropriate load and qualified supervision.'),
  ('Nordic Curl Regression','strength_power','With ankles anchored, lower the torso forward slowly under control, using hands to assist as needed.','Eccentric hamstring strength','High school through adult',3,'5 reps',array['Lower as slowly as you can control','Assist with the hands when needed'],array['Dropping quickly','Progressing load too fast'],'Highly demanding. Progress slowly and expect soreness. Skip on hamstring pain.'),
  ('Rear-Foot-Elevated Split Squat','strength_power','With the back foot elevated, lower into a split squat through a comfortable range and return.','Single-leg strength','High school through adult',3,'6 each side',array['Control the descent','Push through the whole front foot'],array['Using excessive load','Letting the front knee cave in'],'Use appropriate load and qualified supervision.'),
  ('Suitcase Carry','strength_power','Carry a single weight at one side, walking slowly while staying upright and level.','Trunk and pelvis control','Youth through adult',3,'20 metres each side',array['Stay tall and level','Do not lean away from the weight'],array['Leaning to counterbalance','Rushing the walk'],'Use a manageable weight and a clear walking path.'),
  ('Dead Bug with Full Exhale','strength_power','On your back, extend opposite arm and leg slowly while exhaling fully and keeping the low back down.','Core and pelvis control','Youth through adult',3,'6 each side',array['Exhale fully','Keep the low back flat'],array['Letting the back arch','Moving too quickly'],'Reduce range if the low back lifts.'),
  ('Chest-Supported Row','strength_power','Lying chest-down on an incline, row a light weight while keeping the shoulder blades controlled.','Shoulder-blade control','High school through adult',3,'8 reps',array['Lead with the shoulder blade','Control the return'],array['Yanking the weight','Shrugging'],'Use light load and qualified supervision.'),
  ('Lateral Bound to Stick','strength_power','Bound sideways and stick the landing on one leg for two counts before the next rep.','Lateral power and landing control','High school through adult',3,'4 each side',array['Stick the landing completely','Full recovery between reps'],array['Rushing reps together','Landing stiff'],'Full rest between reps. Non-slip surface.'),
  ('Broad Jump to Stick','strength_power','Jump forward with both legs and stick the landing under control.','Lower-body power','High school through adult',3,'4 reps',array['Land softly','Stop completely before the next rep'],array['Chaining jumps together','Landing stiff-legged'],'Full rest between reps. Non-slip surface.')
)
insert into public.drills(name, category, description, what_it_trains, athlete_type, sets, reps, coaching_cues, common_mistakes, contraindications, is_active, is_demo)
select name, category::drill_category, description, trains, athlete_type, sets, reps, cues, mistakes, safety, true, false
from seed
where not exists (select 1 from public.drills d where lower(d.name) = lower(seed.name));

-- Confirm coverage. Every throwing category should have at least three so the
-- plan can pick a primary and a separate repeatability drill without reusing
-- the same movement.
select category, count(*) as drills
from public.drills
group by category
order by category;
