-- Automatic report draft synchronization support and expanded Pitch Nav drill library.
-- Phase images are video-based candidates and require staff verification before release.

create unique index if not exists uq_scorecard_report_category
  on public.scorecard_categories(report_id, category);
create unique index if not exists uq_position_report_position
  on public.position_screenshots(report_id, position);

-- Seed a broad coaching library without duplicating existing drill names.
with seed(name, category, description, trains, athlete_type, sets, reps, cues, mistakes, safety) as (
  values
  ('Stride-Line Tape Drill','direction','Use a tape line from the rubber toward the target and rehearse controlled strides that finish near the line.','Directional consistency and landing awareness','All levels',3,'6 reps',array['Move the center of mass toward the target','Land naturally without forcing the foot'],array['Reaching for the line','Changing normal stride length'],'Stop if the drill causes pain; this is a movement-awareness drill.'),
  ('Walk-In Direction Throws','direction','Take two relaxed walking steps into a controlled throw while maintaining momentum toward the target.','Linear momentum and direction','High school through adult',3,'5 throws',array['Keep momentum smooth','Finish toward the target'],array['Rushing the walk-in','Falling off to the glove side'],'Use only within an existing pain-free throwing program.'),
  ('Closed-Lane Throws','direction','Create a visual lane with two cones and deliver the pitch while keeping the body moving through the lane.','Direction and finish pattern','All levels',3,'6 throws',array['Own the lane','Let the back side finish naturally'],array['Steering the ball','Forcing a straight landing foot'],'Use adequate spacing and a safe throwing area.'),
  ('Tempo Step Drill','rhythm','Use a small step-behind into the delivery to feel continuous, unhurried momentum.','Delivery rhythm and tempo','All levels',3,'6 reps',array['Stay fluid','Avoid pauses after movement begins'],array['Moving too fast','Losing posture'],'Begin at low intensity and progress only when controlled.'),
  ('Three-Count Delivery','rhythm','Rehearse leg lift, move-out, and finish on a consistent three-count cadence.','Repeatable rhythm','Youth through high school',3,'8 dry reps',array['Use the same cadence each rep','Stay balanced but not static'],array['Freezing at balance','Counting faster each rep'],'Dry drill; keep effort controlled.'),
  ('Rock-Back Rhythm Throw','rhythm','Rock gently into the back hip, reverse direction, and complete a controlled throw.','Load-to-move transition','All levels',3,'6 throws',array['Make the reversal smooth','Keep the head quiet'],array['Sitting too deep','Drifting away from the target'],'Use at moderate intensity.'),
  ('Hershiser Wall Drill','lower_half_sequencing','Stand sideways near a padded wall and move the lead hip toward it before the upper body opens.','Hip lead and lower-half sequencing','High school through adult',3,'8 reps',array['Lead with the hip','Keep the torso stacked'],array['Reaching with the shoulder','Crashing into the wall'],'Use a padded surface and no ball; avoid impact.'),
  ('Glute-Load Hold','lower_half_sequencing','Pause briefly in a controlled rear-hip load, then move smoothly into stride.','Rear-hip loading awareness','All levels',3,'6 reps',array['Feel pressure through the whole foot','Move out of the hip smoothly'],array['Collapsing the back knee','Holding the breath'],'Do not force hip depth or range.'),
  ('Step-Behind Throw','lower_half_sequencing','Use a step-behind entry to organize lower-half momentum before the arm accelerates.','Ground-up sequencing','High school through adult',3,'5 throws',array['Let the legs start the motion','Keep arm action relaxed'],array['Overstriding','Throwing before the feet organize'],'Start at low intensity in a safe throwing lane.'),
  ('Lead-Leg Isometric Hold','lead_leg_stability','Assume a comfortable post-contact position and hold it while maintaining level hips and trunk control.','Lead-leg and trunk stability','High school through adult',3,'20 seconds',array['Keep the knee softly stable','Maintain level hips'],array['Locking the knee','Leaning backward'],'Bodyweight only; stop with knee pain.'),
  ('Foot-Strike Freeze','lead_leg_stability','Move through a dry delivery and freeze at a comfortable foot-strike position before finishing.','Foot-contact control','All levels',3,'6 reps',array['Land under control','Keep the head between the feet'],array['Forcing the foot angle','Collapsing after contact'],'Dry drill at controlled speed.'),
  ('Split-Stance Med-Ball Hold','lead_leg_stability','In a split stance, hold a light medicine ball at the chest while resisting unwanted front-knee movement.','Lead-side stability','High school through adult',3,'20 seconds',array['Brace through the trunk','Keep pressure through the lead foot'],array['Using a ball that is too heavy','Knee collapsing inward'],'Use a light load and qualified supervision.'),
  ('Separation Pause Drill','trunk_rotation','Rehearse lower-body rotation into a brief controlled pause before allowing the trunk to follow.','Hip-to-trunk sequencing awareness','High school through adult',3,'6 dry reps',array['Let hips lead slightly','Keep the movement smooth'],array['Forcing extreme separation','Holding a painful position'],'Never force range or use this to chase an angle.'),
  ('Open-Stance Med-Ball Rotation','trunk_rotation','Rotate a light medicine ball from a stable athletic stance toward a wall or partner.','Rotational power and control','High school through adult',3,'5 each side',array['Rotate from the ground up','Finish balanced'],array['Overarching the back','Using arms only'],'Use a light ball, clear area, and supervision.'),
  ('Cable Lift Pattern','trunk_rotation','Perform a controlled diagonal cable lift with hips and trunk moving together.','Trunk control and rotational strength','College through adult',3,'8 each side',array['Move through the trunk','Control the return'],array['Using excessive load','Twisting through pain'],'Qualified strength supervision recommended.'),
  ('Connection Ball Drill','arm_timing','Place a small towel or connection ball near the throwing-side upper arm during a dry delivery to feel arm-trunk timing.','Arm and trunk connection','High school through adult',3,'6 dry reps',array['Keep the arm relaxed','Let the ball fall naturally'],array['Squeezing the object','Pinning the elbow'],'Dry drill only; do not force elbow position.'),
  ('Pivot Throw','arm_timing','From a narrow pivot stance, rotate and make controlled throws while emphasizing relaxed arm acceleration.','Arm timing with trunk rotation','High school through adult',3,'6 throws',array['Turn then throw','Keep the hand relaxed'],array['Spinning off balance','Muscling the ball'],'Low-to-moderate intensity only.'),
  ('Figure-Eight Arm Path','arm_timing','Trace a relaxed figure-eight pattern with the throwing arm before blending into a dry delivery.','Arm-path fluidity','All levels',2,'8 reps',array['Stay loose','Use a pain-free range'],array['Making the circle too large','Forcing shoulder rotation'],'No weighted ball; stop with discomfort.'),
  ('Reverse Throw Decel Drill','deceleration','Use a very light implement or towel to rehearse the reverse pattern slowly and under control.','Posterior shoulder control awareness','College through adult',2,'6 reps',array['Move slowly','Control every phase'],array['Using too much load','Moving explosively'],'Only with qualified coaching; never use a baseball at speed.'),
  ('Balanced Finish Hold','deceleration','Complete a dry or low-intent delivery and hold the finish for two seconds.','Finish control and deceleration','All levels',3,'6 reps',array['Let the torso finish naturally','Regain balance without stiffness'],array['Stopping the arm early','Forcing a pose'],'Do not use a forced finish if it alters natural motion.'),
  ('Step-Through Finish','deceleration','At low intensity, allow the back leg to step through naturally after release while maintaining control.','Momentum absorption','High school through adult',3,'5 throws',array['Let momentum continue','Keep eyes near the target'],array['Jumping through','Cutting off the arm'],'Use only in a clear throwing area.'),
  ('Nine-Box Command','command','Divide the strike zone into nine targets and record misses and hits at controlled intent.','Location awareness and command','High school through adult',3,'9 pitches',array['Commit to one target','Track patterns, not perfection'],array['Changing mechanics to aim','Ignoring workload'],'Counts toward normal pitch workload.'),
  ('Fastball Lane Challenge','command','Alternate arm-side and glove-side fastball lanes while keeping the same delivery intent.','Fastball command consistency','High school through adult',3,'8 pitches',array['Use the same tempo','Finish through the catcher'],array['Slowing the arm','Aiming with the body'],'Counts toward normal pitch workload.'),
  ('Release Window Net','command','Use a safe visual target on a net to compare intended and actual ball flight.','Release-window awareness','All levels',3,'8 throws',array['Focus beyond the release point','Keep normal intent'],array['Trying to place the hand','Changing stride to aim'],'Use a secure net and safe spacing.'),
  ('Half-Kneeling Hip Flexor Mobility','mobility','Use a supported half-kneeling position and gently move forward within a comfortable range.','Hip-flexor mobility','All levels',2,'30 seconds each side',array['Keep ribs stacked','Use a gentle stretch'],array['Arching the low back','Forcing range'],'No bouncing; stop with pain.'),
  ('Open-Book Rotation','mobility','Lie on the side with knees supported and rotate the upper trunk through a comfortable range.','Thoracic rotation mobility','All levels',2,'8 each side',array['Breathe slowly','Keep knees supported'],array['Forcing the shoulder to the floor','Moving through pain'],'Use only a comfortable range.'),
  ('Ankle Rocker Mobility','mobility','In a supported split stance, move the knee forward over the foot without lifting the heel.','Ankle mobility for landing control','All levels',2,'10 each side',array['Keep the heel down','Track knee over toes'],array['Foot collapsing inward','Forcing depth'],'Stop with ankle or knee pain.'),
  ('Lateral Bound Stick','strength_power','Perform a controlled lateral bound and hold the landing before resetting.','Single-leg power and landing control','High school through adult',3,'4 each side',array['Land quietly','Own the position before resetting'],array['Chasing distance','Knee collapsing inward'],'Use non-slip surface and qualified supervision.'),
  ('Split-Squat Strength','strength_power','Perform a controlled split squat through a comfortable range while maintaining trunk and knee alignment.','Single-leg strength','High school through adult',3,'6 each side',array['Control the descent','Push through the whole foot'],array['Using excessive load','Losing knee alignment'],'Use appropriate load and qualified supervision.'),
  ('Medicine-Ball Shotput','strength_power','From an athletic stance, drive a light medicine ball toward a wall using coordinated legs and trunk.','Rotational power transfer','High school through adult',3,'5 each side',array['Drive from the ground','Finish balanced'],array['Using arms only','Using a ball that is too heavy'],'Clear the area and use a wall rated for medicine-ball work.')
)
insert into public.drills(name, category, description, what_it_trains, athlete_type, sets, reps, coaching_cues, common_mistakes, contraindications, is_active, is_demo)
select name, category::drill_category, description, trains, athlete_type, sets, reps, cues, mistakes, safety, true, false
from seed
where not exists (select 1 from public.drills d where lower(d.name) = lower(seed.name));
